### ISSUE TITLE
http error, when i use serverless deploy 

### ISSUE THREAD

**Issue by zhaogaiwen** [serverless/serverless-knative#10]
this is my serverless.yml

service: my-knative-java
provider:
name: knative
docker:
username: zhaogaiwen
password: zhao19901013

functions:
hello:
handler: hello-world.dockerfile
context: ./code
plugins:

serverless-knative
this is the exception:

Serverless: Deploying Kubernetes namespace "sls-aws-java-maven-dev"...
Serverless: Deploying Knative service for function "aws-java-maven-hello"...

Http Error ---------------------------------------------

HttpError: HTTP request failed
at Request.localVarRequest [as _callback] (/home/ec2-user/zgw/aws-java-maven/node_modules/@kubernetes/client-node/dist/gen/api/customObjectsApi.js:254:40)
at Request.self.callback (/home/ec2-user/zgw/aws-java-maven/node_modules/request/request.js:185:22)
at Request.emit (events.js:198:13)
at Request.EventEmitter.emit (domain.js:448:20)
at Request. (/home/ec2-user/zgw/aws-java-maven/node_modules/request/request.js:1154:10)
at Request.emit (events.js:198:13)
at Request.EventEmitter.emit (domain.js:448:20)
at IncomingMessage. (/home/ec2-user/zgw/aws-java-maven/node_modules/request/request.js:1076:12)
at Object.onceWrapper (events.js:286:20)
at IncomingMessage.emit (events.js:203:15)
at IncomingMessage.EventEmitter.emit (domain.js:448:20)
at endReadableNT (_stream_readable.js:1145:12)
at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by thecodacus** [comment]
I'm also facing the same issue.

**Comment by tarzzz** [comment]
Still facing the issue. Any pointers..?

**Comment by mjacobsson** [comment]
Same here :( How can I debug/resolve this?

**Comment by stellamargonar** [comment]
Hi, i'm having the same issue.

I installed knative-serving and eventing, using Kourier as networking layer, local kubernetes (v 1.21.2) following the [quick start tutorial](https://www.serverless.com/framework/docs/providers/knative/guide/quick-start/). 

On the function deploy i get 
```
Serverless: Invoke deploy
Serverless: Invoke package
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Building Docker image "undefined/exportless-knative-hello:1626094940829"...
Serverless: Pushing "undefined/exportless-knative-hello:1626094940829" to Container Registry...
Serverless: Deploying Kubernetes namespace "sls-exportless-knative-dev"...
Serverless: Deploying Knative service for function "exportless-knative-hello"...

 Http Error ----------------------------------------------

  HttpError: HTTP request failed
      at Request._callback (/path/to/exportless-knative/node_modules/@serverless/knative-serving/node_modules/@kubernetes/client-node/dist/gen/api/customObjectsApi.js:1626:40)
      at Request.self.callback (/path/to/exportless-knative/node_modules/request/request.js:185:22)
      at Request.emit (events.js:315:20)
      at Request.EventEmitter.emit (domain.js:482:12)
      at Request.<anonymous> (/path/to/exportless-knative/node_modules/request/request.js:1154:10)
      at Request.emit (events.js:315:20)
      at Request.EventEmitter.emit (domain.js:482:12)
      at IncomingMessage.<anonymous> (/path/to/exportless-knative/node_modules/request/request.js:1076:12)
      at Object.onceWrapper (events.js:421:28)
      at IncomingMessage.emit (events.js:327:22)
      at IncomingMessage.EventEmitter.emit (domain.js:482:12)
      at endReadableNT (_stream_readable.js:1221:12)
      at processTicksAndRejections (internal/process/task_queues.js:84:21)
```


i tried adding a console log right before the error and i can see that the request failing is a PATCH returning `404 - page not found` (here the details)

```
{
  method: 'PATCH',
  qs: {},
  headers: {
    Accept: 'application/json',
    'Content-Type': 'application/merge-patch+json'
  },
  uri: 'https://kubernetes.docker.internal:6443/apis/serving.knative.dev/v1alpha1/namespaces/sls-exportless-knative-dev/services/exportless-knative-hello',
  useQuerystring: false,
  json: true,
  body: {
    apiVersion: 'serving.knative.dev/v1alpha1',
    kind: 'Service',
    metadata: {
      name: 'exportless-knative-hello',
      namespace: 'sls-exportless-knative-dev'
    },
    spec: { template: [Object] }
  },
  ca: ....
}
```


Do you have any suggestion on what could be the problem?
i also tried previously with Istio and the result is the same..

**Comment by batjko** [comment]
Same here, on a fresh Docker-Desktop installation.

I also get an unrecognized provider warning, not sure that's related at all?

```bash
$ sls deploy

Serverless: Configuration warning: Unrecognized provider 'knative'
Serverless:  
Serverless: You're relying on provider plugin which doesn't provide a validation schema for its config.
Serverless: Please report the issue at its bug tracker linking: https://www.serverless.com/framework/docs/providers/aws/guide/plugins#extending-validation-schema
Serverless: You may turn off this message with "configValidationMode: off" setting
Serverless:  
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Building Docker image "batjko/knative-svc1-hello:1627334320821"...
Serverless: Pushing "batjko/knative-svc1-hello:1627334320821" to Container Registry...
Serverless: Deploying Kubernetes namespace "sls-knative-svc1-dev"...
Serverless: Deploying Knative service for function "knative-svc1-hello"...
 
 Http Error ----------------------------------------------
 
  HttpError: HTTP request failed
      at Request._callback (/mnt/d/dev/knative-svc1/node_modules/@kubernetes/client-node/dist/gen/api/customObjectsApi.js:1626:40)
      at Request.self.callback (/mnt/d/dev/knative-svc1/node_modules/request/request.js:185:22)
[...]
```

Serverless docs for Knative don't mention anything about setting up any networking etc, so not sure what's needed here.

**Comment by Richardmbs12** [comment]
Same on my side :(

**Comment by insuusvenerati** [comment]
Are you all testing this with a local kubernetes setup?

**Comment by batjko** [comment]
> Are you all testing this with a local kubernetes setup?

Indeed. In my case the Kubernetes cluster Docker Desktop gives you.

**Comment by cloudops-mboudreau** [comment]
Same for me ... I'm working with a cluster in EKS ...

**Comment by Richardmbs12** [comment]
Same, also using EKS

**Comment by ksingh7** [comment]
Thanks, @medikoo for clarifying the situation on this.

**Comment by inventionlabsSydney** [comment]
@zhaogaiwen you may want to remove your docker-hub credentials from this post....

**Comment by xiaolong2013** [comment]
I have fixed the problem

env:
   node : 16.4.0
   npm: 7.19.0
   docker: Docker version 20.10.12, build e91ed57.  docker-desktop
   k8s: Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.1", GitCommit:"632ed300f2c34f6d6d15ca4cef3d3c7073412212", GitTreeState:"clean", BuildDate:"2021-08-19T15:45:37Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.5", GitCommit:"5c99e2ac2ff9a3c549d9ca665e7bc05a3e18f07e", GitTreeState:"clean", BuildDate:"2021-12-16T08:32:32Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}
  istio: 1.13.0
  knative: 1.2.0

  
<img width="794" alt="image" src="https://user-images.githubusercontent.com/4131679/155709525-44de2912-b830-4a96-bcd8-2e39b68f5d52.png">

three modify
     1. serverless.yml add  configValidationMode: off
     2. my-service/node_modules/@serverless/knative-serving/serverless.js  update from knativeVersion: 'v1alpha1' to
         knativeVersion: 'v1',
     3.  my-service/node_modules/@serverless/knative-serving/serverless.js update
         // "private" methods
        async getIstioIngressIp(k8s) {
          const res = await k8s.readNamespacedService('istio-ingressgateway', 'istio-system')
          //return res.body.status.loadBalancer.ingress[0].ip
          return res.body.status.loadBalancer.ingress[0].hostname
        }

**Comment by xiaolong2013** [comment]
> Hi, i'm having the same issue.
> 
> I installed knative-serving and eventing, using Kourier as networking layer, local kubernetes (v 1.21.2) following the [quick start tutorial](https://www.serverless.com/framework/docs/providers/knative/guide/quick-start/).
> 
> On the function deploy i get
> 
> ```
> Serverless: Invoke deploy
> Serverless: Invoke package
> Serverless: Packaging service...
> Serverless: Excluding development dependencies...
> Serverless: Building Docker image "undefined/exportless-knative-hello:1626094940829"...
> Serverless: Pushing "undefined/exportless-knative-hello:1626094940829" to Container Registry...
> Serverless: Deploying Kubernetes namespace "sls-exportless-knative-dev"...
> Serverless: Deploying Knative service for function "exportless-knative-hello"...
> 
>  Http Error ----------------------------------------------
> 
>   HttpError: HTTP request failed
>       at Request._callback (/path/to/exportless-knative/node_modules/@serverless/knative-serving/node_modules/@kubernetes/client-node/dist/gen/api/customObjectsApi.js:1626:40)
>       at Request.self.callback (/path/to/exportless-knative/node_modules/request/request.js:185:22)
>       at Request.emit (events.js:315:20)
>       at Request.EventEmitter.emit (domain.js:482:12)
>       at Request.<anonymous> (/path/to/exportless-knative/node_modules/request/request.js:1154:10)
>       at Request.emit (events.js:315:20)
>       at Request.EventEmitter.emit (domain.js:482:12)
>       at IncomingMessage.<anonymous> (/path/to/exportless-knative/node_modules/request/request.js:1076:12)
>       at Object.onceWrapper (events.js:421:28)
>       at IncomingMessage.emit (events.js:327:22)
>       at IncomingMessage.EventEmitter.emit (domain.js:482:12)
>       at endReadableNT (_stream_readable.js:1221:12)
>       at processTicksAndRejections (internal/process/task_queues.js:84:21)
> ```
> 
> i tried adding a console log right before the error and i can see that the request failing is a PATCH returning `404 - page not found` (here the details)
> 
> ```
> {
>   method: 'PATCH',
>   qs: {},
>   headers: {
>     Accept: 'application/json',
>     'Content-Type': 'application/merge-patch+json'
>   },
>   uri: 'https://kubernetes.docker.internal:6443/apis/serving.knative.dev/v1alpha1/namespaces/sls-exportless-knative-dev/services/exportless-knative-hello',
>   useQuerystring: false,
>   json: true,
>   body: {
>     apiVersion: 'serving.knative.dev/v1alpha1',
>     kind: 'Service',
>     metadata: {
>       name: 'exportless-knative-hello',
>       namespace: 'sls-exportless-knative-dev'
>     },
>     spec: { template: [Object] }
>   },
>   ca: ....
> }
> ```
> 
> Do you have any suggestion on what could be the problem? i also tried previously with Istio and the result is the same..

Refer to my  comment

**Comment by xiaolong2013** [comment]
> Same here, on a fresh Docker-Desktop installation.
> 
> I also get an unrecognized provider warning, not sure that's related at all?
> 
> ```shell
> $ sls deploy
> 
> Serverless: Configuration warning: Unrecognized provider 'knative'
> Serverless:  
> Serverless: You're relying on provider plugin which doesn't provide a validation schema for its config.
> Serverless: Please report the issue at its bug tracker linking: https://www.serverless.com/framework/docs/providers/aws/guide/plugins#extending-validation-schema
> Serverless: You may turn off this message with "configValidationMode: off" setting
> Serverless:  
> Serverless: Packaging service...
> Serverless: Excluding development dependencies...
> Serverless: Building Docker image "batjko/knative-svc1-hello:1627334320821"...
> Serverless: Pushing "batjko/knative-svc1-hello:1627334320821" to Container Registry...
> Serverless: Deploying Kubernetes namespace "sls-knative-svc1-dev"...
> Serverless: Deploying Knative service for function "knative-svc1-hello"...
>  
>  Http Error ----------------------------------------------
>  
>   HttpError: HTTP request failed
>       at Request._callback (/mnt/d/dev/knative-svc1/node_modules/@kubernetes/client-node/dist/gen/api/customObjectsApi.js:1626:40)
>       at Request.self.callback (/mnt/d/dev/knative-svc1/node_modules/request/request.js:185:22)
> [...]
> ```
> 
> Serverless docs for Knative don't mention anything about setting up any networking etc, so not sure what's needed here.
before fix i have problem as same as you

**Comment by xiaolong2013** [comment]
> this is my serverless.yml
> 
> service: my-knative-java provider: name: knative docker: username: zhaogaiwen password: zhao19901013
> 
> functions: hello: handler: hello-world.dockerfile context: ./code plugins:
> 
> serverless-knative this is the exception:
> 
> Serverless: Deploying Kubernetes namespace "sls-aws-java-maven-dev"... Serverless: Deploying Knative service for function "aws-java-maven-hello"...
> 
> Http Error ---------------------------------------------
> 
> HttpError: HTTP request failed at Request.localVarRequest [as _callback] (/home/ec2-user/zgw/aws-java-maven/node_modules/@kubernetes/client-node/dist/gen/api/customObjectsApi.js:254:40) at Request.self.callback (/home/ec2-user/zgw/aws-java-maven/node_modules/request/request.js:185:22) at Request.emit (events.js:198:13) at Request.EventEmitter.emit (domain.js:448:20) at Request. (/home/ec2-user/zgw/aws-java-maven/node_modules/request/request.js:1154:10) at Request.emit (events.js:198:13) at Request.EventEmitter.emit (domain.js:448:20) at IncomingMessage. (/home/ec2-user/zgw/aws-java-maven/node_modules/request/request.js:1076:12) at Object.onceWrapper (events.js:286:20) at IncomingMessage.emit (events.js:203:15) at IncomingMessage.EventEmitter.emit (domain.js:448:20) at endReadableNT (_stream_readable.js:1145:12) at process._tickCallback (internal/process/next_tick.js:63:19)

Refer to me
